server:
    port: 8079
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-ms
            uri: lb://USER-MS
            predicates:
              - Path=/api/user-ms/**

          - id: parking-ms
            uri: lb://PARKING-MS
            predicates:
              - Path=/api/parking-ms/**

          - id: mail-ms
            uri: lb://MAIL-MS
            predicates:
              - Path=/api/mail-ms/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

