spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb://localhost:27017/email

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRE_TIME}

springdoc:
  writer-with-default-pretty-printer: true
  api-docs:
    enabled: true
    version: "openapi_3_0"

  swagger-ui:
    enabled: true
    operations-sorter: "method"
    tags-sorter: "alpha"
    display-request-duration: true
    path: /swagger-ui.html

client:
  url: http://localhost:8080
  emailservice:
    email: ${SERVICE_EMAIL}
    url: http://localhost:8081


mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
