spring:
  application:
    name: mail-ms
  config:
    import: optional:file:.env[.properties]
  datasource:
    password: ${POSTGRES_USER}
    username: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URI}

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRE_TIME}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  writer-with-default-pretty-printer: true
  api-docs:
    enabled: true
    version: "openapi_3_0"

  swagger-ui:
    enabled: true
    operations-sorter: "method"
    tags-sorter: "alpha"
    display-request-duration: true
    path: /swagger-ui.html

client:
  url: http://ms-user:8080
  emailservice:
    email: ${SERVICE_EMAIL}
    url: http://ms-parking:8081


mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}
