server:
  servlet:
    context-path: /api/mail-ms/
  error:
    include-message: always
  port: 8082

spring:
  profiles:
    include:
      - mq
    active: dev
  jackson:
    time-zone: America/Bogota
    date-format: yyyy-MM-dd hh:mm:ss a