spring:

  config:
    import: optional:file:.env[.properties]

  datasource:
    password: ${POSTGRES_USER}
    username: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URI}

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRE_TIME}

user:
  client:
    url: http://ms-user:8080
    url-email: http://ms-mail:8082
